#!/usr/bin/env python3
"""
Level-authoring tool for SUPER COBOL BROS.

This is a convenience *editor*: it emits the plain-text .lvl DATA files
that the COBOL game parses at runtime.  The .lvl files are the real
deliverable and can be edited by hand in any text editor; this script
just makes it easy to keep 22-row grids aligned.

Grid legend (must match src/copy/constants.cpy and levelload):
  space empty   '=' ground   '#' hard block   '|' pipe(solid)
  '?' question  'o' coin      'P' spawn        'G' goomba
  'M' mushroom  '^' spikes    'F' goal flag    '!' flag pole(decor)

Rows are 0-indexed here (0 = top / sky, 21 = bottom).
"""
import os

FIELD_ROWS = 22
LEVELS_DIR = os.path.join(os.path.dirname(__file__), "..", "levels")


class Level:
    def __init__(self, name, width, time):
        self.name = name
        self.width = width
        self.time = time
        self.grid = [[" "] * width for _ in range(FIELD_ROWS)]
        self.platforms = []  # (id, col, row, axis, range, speed)

    def put(self, r, c, ch):
        if 0 <= r < FIELD_ROWS and 0 <= c < self.width:
            self.grid[r][c] = ch

    def hline(self, r, c1, c2, ch):
        for c in range(c1, c2 + 1):
            self.put(r, c, ch)

    def vline(self, c, r1, r2, ch):
        for r in range(r1, r2 + 1):
            self.put(r, c, ch)

    def rect(self, r1, r2, c1, c2, ch):
        for r in range(r1, r2 + 1):
            self.hline(r, c1, c2, ch)

    def text(self, r, c, s):
        for i, ch in enumerate(s):
            self.put(r, c + i, ch)

    def platform(self, pid, col, row, axis, rng, speed):
        self.platforms.append((pid, col, row, axis, rng, speed))

    def render(self):
        out = []
        out.append("# %s -- generated by tools/make_levels.py" % self.name)
        out.append("# legend: = ground  # hard  | pipe  ? block  o coin")
        out.append("#         P spawn  G goomba  M mushroom  ^ spikes  F flag")
        out.append("NAME %s" % self.name)
        out.append("WIDTH %d" % self.width)
        out.append("TIME %d" % self.time)
        out.append("GRID")
        for row in self.grid:
            # rstrip is safe: the COBOL parser pads short rows with spaces.
            out.append("".join(row).rstrip())
        for (pid, col, row, axis, rng, speed) in self.platforms:
            # grid glyphs are placed 0-indexed and become 1-indexed in the
            # COBOL grid; platform coords use the SAME 0-indexed convention
            # here and are converted to the game's 1-indexed space with +1.
            out.append("PLATFORM %d %d %d %s %d %d"
                       % (pid, col + 1, row + 1, axis, rng, speed))
        return "\n".join(out) + "\n"

    def save(self, filename):
        path = os.path.join(LEVELS_DIR, filename)
        with open(path, "w") as f:
            f.write(self.render())
        print("wrote", path)


def base_ground(lv, pits=()):
    """Solid floor on the bottom two rows, minus any pit column ranges."""
    lv.hline(20, 0, lv.width - 1, "=")
    lv.hline(21, 0, lv.width - 1, "=")
    for (c1, c2) in pits:
        for c in range(c1, c2 + 1):
            lv.put(20, c, " ")
            lv.put(21, c, " ")


def goal(lv, col):
    """Exactly one goal flag (F) at ground level, decorative pole above.
    The loader requires exactly one 'F', so the pole uses '!' only."""
    lv.put(19, col, "F")
    lv.vline(col, 13, 18, "!")


def coin_row(lv, r, c1, c2, step=1):
    for c in range(c1, c2 + 1, step):
        lv.put(r, c, "o")


# ----------------------------------------------------------------------
# 1-1  Gentle tutorial: flat ground, coins, one block, one pipe,
#      two goombas, one small pit.  Teaches run / jump / stomp / coins.
# ----------------------------------------------------------------------
def level_1_1():
    lv = Level("1-1", 120, 400)
    base_ground(lv, pits=[(70, 72)])
    lv.put(19, 4, "P")
    coin_row(lv, 19, 14, 18)          # a friendly line of coins to walk over
    lv.put(16, 22, "?")               # first ? block -> a coin
    lv.vline(30, 18, 19, "|")         # a pipe to hop
    lv.put(19, 40, "G")               # goomba to stomp
    coin_row(lv, 15, 69, 73)          # coins arcing over the pit
    lv.put(19, 85, "G")               # a second goomba
    lv.put(16, 95, "?")               # another ? block
    coin_row(lv, 19, 100, 104)
    goal(lv, 114)
    lv.save("world-1-1.lvl")


# ----------------------------------------------------------------------
# 1-2  Introduces floating platforms (static blocks), a mushroom,
#      wider pits, three goombas.
# ----------------------------------------------------------------------
def level_1_2():
    lv = Level("1-2", 140, 380)
    base_ground(lv, pits=[(38, 41), (78, 82)])
    lv.put(19, 3, "P")
    lv.put(16, 12, "?")               # mushroom block (small player -> grow)
    lv.text(16, 12, "?")
    coin_row(lv, 19, 20, 25)
    lv.put(19, 30, "G")
    # floating brick steps over the first pit
    lv.hline(16, 36, 43, "=")
    coin_row(lv, 15, 37, 42)
    lv.put(19, 55, "G")
    lv.put(13, 60, "?")
    lv.vline(48, 17, 19, "|")
    # staircase up
    lv.put(19, 68, "=")
    lv.put(18, 69, "=")
    lv.put(17, 70, "=")
    lv.put(16, 71, "=")
    # bricks across second pit
    lv.hline(17, 77, 83, "=")
    coin_row(lv, 16, 78, 82)
    lv.put(19, 95, "G")
    lv.put(16, 100, "?")
    coin_row(lv, 19, 108, 114)
    lv.put(19, 120, "G")
    goal(lv, 134)
    lv.save("world-1-2.lvl")


# ----------------------------------------------------------------------
# 1-3  Spikes, taller structures, several goombas, high coins.
# ----------------------------------------------------------------------
def level_1_3():
    lv = Level("1-3", 150, 360)
    base_ground(lv, pits=[(55, 58), (95, 99)])
    lv.put(19, 3, "P")
    coin_row(lv, 19, 10, 14)
    lv.put(19, 20, "G")
    lv.put(16, 24, "?")
    # spike pit lined with hazards
    lv.hline(19, 30, 34, "^")
    lv.hline(15, 29, 35, "=")         # a bridge of bricks over the spikes
    coin_row(lv, 14, 30, 34)
    lv.put(19, 44, "G")
    lv.put(19, 46, "G")
    # rising steps toward the first gap
    lv.put(19, 50, "=")
    lv.put(18, 51, "=")
    lv.put(17, 52, "=")
    lv.hline(17, 53, 60, "=")
    coin_row(lv, 16, 55, 58)
    lv.put(19, 70, "G")
    lv.put(13, 74, "?")
    lv.put(16, 74, "?")
    # tall pipe
    lv.vline(82, 16, 19, "|")
    lv.vline(83, 16, 19, "|")
    # spikes near second pit
    lv.hline(19, 90, 93, "^")
    lv.hline(15, 94, 101, "=")
    coin_row(lv, 14, 95, 100, 2)
    lv.put(19, 110, "G")
    lv.put(19, 112, "G")
    lv.put(16, 118, "?")
    coin_row(lv, 19, 124, 130)
    goal(lv, 144)
    lv.save("world-1-3.lvl")


# ----------------------------------------------------------------------
# 1-4  The gauntlet: moving platforms over pits, a pit sequence,
#      a mushroom, multiple goombas.
# ----------------------------------------------------------------------
def level_1_4():
    lv = Level("1-4", 175, 340)
    # big pits crossed by ground-level moving platforms (row 20 = surface)
    base_ground(lv, pits=[(40, 58), (94, 116), (140, 146)])
    lv.put(19, 3, "P")
    lv.put(16, 10, "?")               # mushroom early (help for the gauntlet)
    coin_row(lv, 19, 16, 22)
    lv.put(19, 30, "G")
    lv.put(19, 34, "G")
    # ---- first chasm (cols 40-58): a horizontal moving platform ----
    #      rides at the ground surface so you can walk straight on
    lv.platform(1, 40, 20, "H", 16, 1)
    coin_row(lv, 19, 45, 53, 2)       # coins grabbable while riding across
    lv.put(19, 66, "G")
    lv.put(13, 70, "?")
    lv.put(16, 70, "?")
    lv.put(19, 76, "G")
    lv.put(19, 80, "G")
    # a small brick lip before the big chasm
    lv.put(19, 88, "=")
    lv.put(18, 89, "=")
    lv.hline(18, 90, 93, "=")
    # ---- big chasm (cols 94-116): two ground-level moving platforms ----
    lv.platform(2, 94, 20, "H", 10, 1)
    lv.platform(3, 106, 20, "H", 10, 1)
    coin_row(lv, 19, 98, 114, 3)
    lv.put(19, 120, "G")
    lv.put(19, 126, "G")
    lv.put(16, 130, "?")
    coin_row(lv, 19, 133, 138)
    # ---- final short pit ----
    lv.platform(4, 140, 20, "H", 6, 1)
    lv.put(19, 152, "G")
    lv.put(19, 158, "G")
    coin_row(lv, 19, 150, 160, 2)
    lv.put(16, 164, "?")
    goal(lv, 170)
    lv.save("world-1-4.lvl")


if __name__ == "__main__":
    level_1_1()
    level_1_2()
    level_1_3()
    level_1_4()
    print("all levels written.")
